--
-- Create database
--
CREATE DATABASE IF NOT EXISTS board;
GRANT SELECT,INSERT,UPDATE,DELETE ON board.* TO board_root@localhost
IDENTIFIED BY 'board_root';
FLUSH PRIVILEGES;


--
-- Create tables
--

USE board;

CREATE TABLE IF NOT EXISTS thread(
id		INT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id		INT UNSIGNED NOT NULL,
title		VARCHAR(30) NOT NULL,
view		INT UNSIGNED NOT NULL DEFAULT 0,
created		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated		TIMESTAMP NOT NULL,
PRIMARY KEY (id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comment(
id		INT UNSIGNED NOT NULL AUTO_INCREMENT,
thread_id	INT UNSIGNED NOT NULL,
user_id		VARCHAR(20) NOT NULL,
body		TEXT NOT NULL,
created		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated		TIMESTAMP NOT NULL,
PRIMARY KEY(id),
INDEX (thread_id,created)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user(
id		INT UNSIGNED NOT NULL AUTO_INCREMENT,
username	VARCHAR(20) NOT NULL,
password	VARCHAR(20) NOT NULL,
name		VARCHAR(50) NOT NULL,
email		VARCHAR(255) NOT NULL,
type		ENUM('admin','user','banned') DEFAULT "user",
registered	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=InnoDB;
